source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'RCAnalytics_Tests', :exclusive => true do
  pod 'RCAnalytics', :path => '../'

  pod 'Quick', '~> 0.9'
  pod 'Nimble', '~> 3.0'
end
